export const projectsData = [
    {
        id: 1,
        name: 'Movies',
        image: "/project-image/movies.png",
        description: "Movies is a website that allows users to search for movies, view details, and explore trending films. Built with React, JavaScript, and Tailwind CSS, it features a responsive design and utilizes the TMDB API for movie data. The project includes viewing details of movies, displaying many categories and etc.",
        tools: ['JavaScript', 'React', 'Tailwind Css', 'Axios', 'React-Query', 'TMDB API'],
        role: 'Frontend Developer',
        github: 'https://github.com/fenix1409/films',
        demo: 'https://films-kappa-one.vercel.app/',
    },
    {
        id: 4121,
        name: 'QuickGPT - AI Chatbot Platform',
        image: "/project-image/gpt.png",
        description: "QuickGPT is an AI chatbot platform that allows users to interact with an AI assistant for various tasks. Built with React, TypeScript, and Tailwind CSS, it features a sleek, modern design and utilizes OpenAI's GPT-3.5 API for natural language processing. The project includes real-time chat functionality, conversation history, and user authentication using Firebase.",
        tools: ['JavaScript', 'React', 'Tailwind Css', 'Express.js', 'MongoDB', 'OpenAI GPT-3.5', 'Firebase Auth'],
        role: 'Frontend Developer',
        github: 'https://github.com/fenix1409/QuickGPT',
        demo: 'https://quick-gpt-eight-beta.vercel.app/',
    },
    {
        id: 1210,
        name: 'Codeflex AI - Fitness Trainer App',
        image: "/project-image/codeflex.png",
        description: "Codeflex AI is a fitness trainer app that uses AI to provide personalized workout plans and nutrition advice. It features a sleek, modern design built with Next.js and TypeScript, and utilizes Vapi Voice AI for voice interactions. The app is fully responsive and optimized for both dekstop and mobile devices. It integrates Clerk for user authentication and Convex API for backend services, ensuring a seamless user experience.",
        tools: ['TypeScript', 'Next.JS', 'Tailwind Css', 'Vapi Voice AI', 'React-Query', 'Convex API', 'Gemini AI', 'Clerk Authication'],
        role: 'Full Stack Developer',
        github: 'https://github.com/fenix1409/codeflex-ai',
        demo: 'https://codeflex-ai-khaki.vercel.app/',
    },
    {
        id: 1110,
        name: 'Mackbook Pro Platform - 3D Product Showcase',
        image: "/project-image/mackbook.png",
        description: "Apple-style website built with React, Three.js, GSAP, and TailwindCSS. Create immersive 3D product scenes with realistic lighting, scroll-triggered animations, masking effects and smooth animations. Optimized for performance and responsiveness across devices.",
        tools: ['JavaScript', 'Three.JS', 'Tailwind Css', 'React.JS 19', 'Zustand', '3D'],
        role: 'Frontend Developer',
        github: 'https://github.com/fenix1409/Apple-Mackbook-Platform',
        demo: 'https://apple-mackbook-platform.vercel.app/',
    },
    {
        id: 7412,
        name: 'Nike E-Commerce Platform',
        image: "/project-image/Nike.png",
        description: "A full-stack Nike-inspired e-commerce platform featuring secure user authentication, dynamic product filtering, shopping cart persistence, and wishlist functionality. Built with Next.js App Router for optimized performance, TypeScript for type safety, and Redux Toolkit for efficient state management. Features a responsive design with seamless animations and modern UI components.",
        tools: ['Next.js', 'Neon', 'Better Auth', 'TypeScript', 'Tailwind CSS', 'Zustand', 'Devin AI', 'Drizzle ORM'],
        github: 'https://github.com/fenix1409/E-Commerce-Nike',
        demo: "https://e-commerce-nike-ashy.vercel.app/",
        role: 'Full Stack Developer'
    },
    {
        id: 3232,
        name: 'SaaS App - LMS Platform',
        image: "/project-image/saas.png",
        description: "Saas LMC is a modern AI companion platform built with Next.js where users can create personalized AI assistants, chat with them in real-time, and manage their conversation history. Features secure authentication, role-based permissions, and a responsive design.",
        tools: ['Next.js', 'Supabase', 'Clerk Auth', 'TypeScript', 'Tailwind CSS', 'Sentrty', 'VAPI Voice AI', 'OpenAI', 'Shadcn UI'],
        github: 'https://github.com/fenix1409/Saas-AI',
        demo: "https://saas-ai-eight-umber.vercel.app/",
        role: 'Full Stack Developer'
    },
    // {
    //     id: 2,
    //     name: 'Picnick',
    //     image: "/project-image/picnick.png",
    //     description: 'Picnick is a modern web application designed for sharing and discovering picnic spots. It features a user-friendly interface built with React, TypeScript, and Tailwind CSS. The project utilizes React Query for efficient data fetching and state managenent, and Axios for API requests.',
    //     tools: ['React', 'Tailwind', 'CSS', 'TypeScript', 'Redux-toolkit', 'React-Query', 'Axios'],
    //     github: 'https://github.com/fenix1409/Picnik',
    //     demo: "https://www.piknicuz.com/",
    //     role: 'Frontend Developer',
    // },
    {
        id: 3,
        name: 'Al-Muamalat',
        image: "/project-image/al-muamalat.png",
        description: 'Al-Muamalat is a modern web application designed for managing financial transactions and services. It features a user-friendly interface built with React, TypeScript, and Tailwind CSS. The project utilizes React Query for efficient data fetching and state management, and Axios for API requests. The application includes features such as transaction history, account management, and financial analytics.',
        tools: ['React JS', 'Tailwind CSS', 'CSS', 'TypeScript', 'React-Query', 'Axios', 'Framer-motion', 'Swiper'],
        // github: 'https://github.com/fenix1409/al-muamalat',
        demo: "https://www.al-muamalat.uz/",
        role: 'Frontend Developer',
    },
    // {
    //     id: 4,
    //     name: 'Segway',
    //     image: "/project-image/segway.png",
    //     description: "I have designed and developed website called Segway. I created the UI using React, Typescript, TailwindCSS. I developed the API using db.json. Users can view the products(scooters and accessories), add them to the cart, and place an order. I added multiple languages, English and Uzbek. I deployed the front-end app to Netlify",
    //     tools: ['React', 'Vite', 'React-Query', 'Axios', "TypeScript", "Tailwind CSS", "React-Router", "Antd", "Swiper"],
    //     github: 'https://github.com/fenix1409/SegWay',
    //     demo: 'https://seg-way.vercel.app/',
    //     role: 'Frontend Developer',
    // },
    // {
    //     id: 5,
    //     name: 'Robotics',
    //     image: "/project-image/robotics.png",
    //     description: "I designed and developed website called Robotics. Robotics is a learning platform that offers a wide range of courses in robotics and automation. The platform features user-friendly, responsive design, connected to google sheets for data management. It's built with Vite + Typescript, Tailwind CSS, and React Query for efficient data fetching.",
    //     tools: ['React', 'React-Query', "TypeScript", "Tailwind CSS", "Google Sheets", "Swiper"],
    //     github: 'https://github.com/fenix1409/Robotics',
    //     demo: 'https://robotics-umber.vercel.app/',
    //     role: 'Frontend Developer'
    // },
    // {
    //     id: 6,
    //     name: 'Ashyo',
    //     image: "/project-image/ashyo.png",
    //     description: "I have designed and developed website called Ashyo. Ashyo is an e-commerce platform designed for seamless online shopping. It includes user authentication, a product catalog, cart management, and a wishlist. Built with Next.js, React, TypeScript, Tailwind CSS, Redux Toolkit, React Query, Hero-UI,  and Axios, it ensures a smooth, responsive, and efficient user experience.",
    //     tools: ['Next.js', 'Tailwind Css', 'TypeScript', 'Redux-toolkit', 'React Query', 'Hero UI', 'Axios', 'Swiper'],
    //     github: 'https://github.com/fenix1409/ashyo_fullstack',
    //     role: 'Frontend Developer'
    // }
];


// Do not remove any property.
// Leave it blank instead as shown below

// {
//     id: 1,
//     name: '',
//     description: "",
//     tools: [],
//     role: '',
//     code: '',
//     demo: '',
// },
